import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

  // === 010 - MANUAL ATUAL (o teu sidebar detalhado) ===
  manualAtual: [
        { type: 'doc', id: 'sbd-manual/index', label: 'Índice' },
        {
          type: 'category',
          label: '0-Fundamentos do Manual',
          link: { type: 'doc', id: 'sbd-manual/fundamentos/intro' },
          items: [
            'sbd-manual/fundamentos/como-usar',
            {
              type: 'category',
              label: 'Roles do SbD–ToE',
              items: [{ type: 'autogenerated', dirName: '010-sbd-manual/00-fundamentos/roles-responsabilidades' }],
              link: { type: 'doc', id: 'sbd-manual/fundamentos/roles-responsabilidades/intro' },
            },
            'sbd-manual/fundamentos/baseline',
          ],
        },
        {
          type: 'category',
          label: '1-Classificaçao das Aplicações',
          link: { type: 'doc', id: 'sbd-manual/classificacao-aplicacoes/intro' },
          items: [
            'sbd-manual/classificacao-aplicacoes/pre-note',
            'sbd-manual/classificacao-aplicacoes/aplicacao-lifecycle',
            'sbd-manual/classificacao-aplicacoes/policies-relevantes',
            {
              type: 'category',
              label: 'Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '010-sbd-manual/01-classificacao-aplicacoes/addon' }],
            },
            'sbd-manual/classificacao-aplicacoes/recomendacoes-avancadas',
          ],
        },
        {
          type: 'category',
          label: '2-Requisitos de Segurança',
          link: { type: 'doc', id: 'sbd-manual/requisitos-seguranca/intro' },
          items: [
            'sbd-manual/requisitos-seguranca/rationale-catalogo',
            'sbd-manual/requisitos-seguranca/aplicacao-lifecycle',
            'sbd-manual/requisitos-seguranca/policies-relevantes',
            {
              type: 'category',
              label: 'Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '010-sbd-manual/02-requisitos-seguranca/addon' }],
            },
            'sbd-manual/requisitos-seguranca/recomendacoes-avancadas',
          ],
        },
        {
          type: 'category',
          label: '3-Threat Modeling',
          link: { type: 'doc', id: 'sbd-manual/threat-modeling/intro' },
          items: [
            'sbd-manual/threat-modeling/aplicacao-lifecycle',
            'sbd-manual/threat-modeling/policies-relevantes',
            {
              type: 'category',
              label: 'Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '010-sbd-manual/03-threat-modeling/addon' }],
            },
            'sbd-manual/threat-modeling/exemplo-privacidade-lindunn',
            'sbd-manual/threat-modeling/exemplos-aplicacao-stride',
          ],
        },
        {
          type: 'category',
          label: '4-Arquitetura Segura',
          link: { type: 'doc', id: 'sbd-manual/arquitetura-segura/intro' },
          items: [
            'sbd-manual/arquitetura-segura/aplicacao-lifecycle',
            'sbd-manual/arquitetura-segura/policies-relevantes',
            {
              type: 'category',
              label: 'Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '010-sbd-manual/04-arquitetura-segura/addon' }],
            },
            'sbd-manual/arquitetura-segura/recomendacoes-avancadas',
          ],
        },
        {
          type: 'category',
          label: '5-Controlo de Dependências (SBOM, SCA)',
          link: { type: 'doc', id: 'sbd-manual/dependencias-sbom-sca/intro' },
          items: [
            'sbd-manual/dependencias-sbom-sca/aplicacao-lifecycle',
            'sbd-manual/dependencias-sbom-sca/policies-relevantes',
            {
              type: 'category',
              label: 'Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '010-sbd-manual/05-dependencias-sbom-sca/addon' }],
            },
            'sbd-manual/dependencias-sbom-sca/recomendacoes-avancadas',
          ],
        },
        {
          type: 'category',
          label: '6-Desenvolvimento Seguro',
          link: { type: 'doc', id: 'sbd-manual/desenvolvimento-seguro/intro' },
          items: [
            'sbd-manual/desenvolvimento-seguro/aplicacao-lifecycle',
            'sbd-manual/desenvolvimento-seguro/policies-relevantes',            
            {
              type: 'category',
              label: 'Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '010-sbd-manual/06-desenvolvimento-seguro/addon' }],
            },
            'sbd-manual/desenvolvimento-seguro/recomendacoes-avancadas',
          ],
        },
        {
          type: 'category',
          label: '7-CI/CD Seguro',
          link: { type: 'doc', id: 'sbd-manual/cicd-seguro/intro' },
          items: [
            'sbd-manual/cicd-seguro/aplicacao-lifecycle',
            'sbd-manual/cicd-seguro/policies-relevantes',
            {
              type: 'category',
              label: 'Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '010-sbd-manual/07-cicd-seguro/addon' }],
            },
            'sbd-manual/cicd-seguro/recomendacoes-avancadas',
          ],
        },
        {
          type: 'category',
          label: '8-Infrastructure as Code (IaC)',
          link: { type: 'doc', id: 'sbd-manual/iac-infraestrutura/intro' },
          items: [
            'sbd-manual/iac-infraestrutura/pre-intro',
            'sbd-manual/iac-infraestrutura/aplicacao-lifecycle',
            'sbd-manual/iac-infraestrutura/policies-relevantes',
            {
              type: 'category',
              label: 'Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '010-sbd-manual/08-iac-infraestrutura/addon' }],
            },
            'sbd-manual/iac-infraestrutura/recomendacoes-avancadas',
          ],
        },
        {
          type: 'category',
          label: '9-Containers e Imagens',
          link: { type: 'doc', id: 'sbd-manual/containers-imagens/intro' },
          items: [
            'sbd-manual/containers-imagens/aplicacao-lifecycle',
            'sbd-manual/containers-imagens/policies-relevantes',
            {
              type: 'category',
              label: 'Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '010-sbd-manual/09-containers-imagens/addon' }],
            },
            'sbd-manual/containers-imagens/exemplo-pipeline-container',
          ],
        },
        {
          type: 'category',
          label: '10-Testes de Segurança',
          link: { type: 'doc', id: 'sbd-manual/testes-seguranca/intro' },
          items: [
            'sbd-manual/testes-seguranca/aplicacao-lifecycle',
            'sbd-manual/testes-seguranca/policies-relevantes',
            {
              type: 'category',
              label: 'Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '010-sbd-manual/10-testes-seguranca/addon' }],
            },
            'sbd-manual/testes-seguranca/recomendacoes-avancadas',
          ],
        },
        {
          type: 'category',
          label: '11-Deploy Seguro',
          link: { type: 'doc', id: 'sbd-manual/deploy-seguro/intro' },
          items: [
            'sbd-manual/deploy-seguro/aplicacao-lifecycle',
            'sbd-manual/deploy-seguro/policies-relevantes',
            {
              type: 'category',
              label: 'Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '010-sbd-manual/11-deploy-seguro/addon' }],
            },
            'sbd-manual/deploy-seguro/recomendacoes-avancadas',
          ],
        },
        {
          type: 'category',
          label: '12-Monitorização e Operações',
          link: { type: 'doc', id: 'sbd-manual/monitorizacao-operacoes/intro' },
          items: [
            'sbd-manual/monitorizacao-operacoes/aplicacao-lifecycle',
            'sbd-manual/monitorizacao-operacoes/policies-relevantes',
            {
              type: 'category',
              label: 'Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '010-sbd-manual/12-monitorizacao-operacoes/addon' }],
            },
            'sbd-manual/monitorizacao-operacoes/casos-praticos-monitorizacao',
            'sbd-manual/monitorizacao-operacoes/recomendacoes-avancadas',
          ],
        },
        {
          type: 'category',
          label: '13-Formação e Onboarding',
          link: { type: 'doc', id: 'sbd-manual/formacao-onboarding/intro' },
          items: [
            'sbd-manual/formacao-onboarding/aplicacao-lifecycle',
            'sbd-manual/formacao-onboarding/policies-relevantes',
            {
              type: 'category',
              label: 'Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '010-sbd-manual/13-formacao-onboarding/addon' }],
            },
            'sbd-manual/formacao-onboarding/recomendacoes-avancadas',
          ],
        },
        {
          type: 'category',
          label: '14-Governança e Contratação',
          link: { type: 'doc', id: 'sbd-manual/governanca-contratacao/intro' },
          items: [
            'sbd-manual/governanca-contratacao/aplicacao-lifecycle',
            'sbd-manual/governanca-contratacao/policies-relevantes',
            {
              type: 'category',
              label: 'Complemento Técnico',
              items: [{ type: 'autogenerated', dirName: '010-sbd-manual/14-governanca-contratacao/addon' }],
            },
            'sbd-manual/governanca-contratacao/kpis-governanca',
            'sbd-manual/governanca-contratacao/recomendacoes-avancadas',
          ],
        },
      ],

  // === 020 - Assets (Policies, Templates, etc.) ===
  toeAssets: [
    {
      type: 'category',
      label: '🏛️ Assets & Policies Organizacionais',
      link: { type: 'doc', id: 'assets/intro' },
      items: [
        {
          type: 'category',
          label: '🔌 MCP Server (SbD-ToE)',
          link: { type: 'doc', id: 'assets/mcp/intro' },
          items: [
            { type: 'doc', id: 'assets/mcp/quickstart' },
            { type: 'doc', id: 'assets/mcp/instalacao' },
            { type: 'doc', id: 'assets/mcp/skills-agentes' },
            { type: 'doc', id: 'assets/mcp/tools-reference' },
            { type: 'doc', id: 'assets/mcp/resources-prompts' },
            {
              type: 'category',
              label: 'Casos de uso',
              link: { type: 'doc', id: 'assets/mcp/casos-uso/index' },
              items: [
                { type: 'doc', id: 'assets/mcp/casos-uso/auditoria-pr' },
                { type: 'doc', id: 'assets/mcp/casos-uso/codegen-grounded' },
                { type: 'doc', id: 'assets/mcp/casos-uso/threat-modeling' },
                { type: 'doc', id: 'assets/mcp/casos-uso/governance-bootstrap' },
                { type: 'doc', id: 'assets/mcp/casos-uso/onboarding-formacao' },
                { type: 'doc', id: 'assets/mcp/casos-uso/cross-check-conformidade' },
              ],
            },
            { type: 'doc', id: 'assets/mcp/padroes-avancados' },
            { type: 'doc', id: 'assets/mcp/epistemica-anti-patterns' },
            { type: 'doc', id: 'assets/mcp/troubleshooting-faq' },
            { type: 'doc', id: 'assets/mcp/versionamento-roadmap' },
          ],
        },
        {
          type: 'category',
          label: 'Políticas Recomendadas',
          items: [
            {
              type: 'category',
              label: 'Risco',
              items: [
                { type: 'doc', id: 'assets/policies/policy-classificacao-risco' },
                { type: 'doc', id: 'assets/policies/policy-aceitacao-risco' },
                { type: 'doc', id: 'assets/policies/policy-revisao-periodica-risco' },
                { type: 'doc', id: 'assets/policies/policy-gestao-excecoes' },
                { type: 'doc', id: 'assets/policies/policy-excecoes-cve' },
              ],
            },
            {
              type: 'category',
              label: 'Design & Análise',
              items: [
                { type: 'doc', id: 'assets/policies/policy-requisitos-seguranca' },
                { type: 'doc', id: 'assets/policies/policy-threat-modeling' },
                { type: 'doc', id: 'assets/policies/policy-arquitetura-segura' },
              ],
            },
            {
              type: 'category',
              label: 'Supply Chain',
              items: [
                { type: 'doc', id: 'assets/policies/policy-dependencias' },
                { type: 'doc', id: 'assets/policies/policy-sbom' },
                { type: 'doc', id: 'assets/policies/policy-atualizacao-automatica' },
              ],
            },
            {
              type: 'category',
              label: 'Desenvolvimento Seguro',
              items: [
                { type: 'doc', id: 'assets/policies/policy-guidelines-desenvolvimento' },
                { type: 'doc', id: 'assets/policies/policy-revisao-codigo' },
                { type: 'doc', id: 'assets/policies/policy-uso-ferramentas-apoio' },
              ],
            },
            {
              type: 'category',
              label: 'Pipeline & Entrega',
              items: [
                { type: 'doc', id: 'assets/policies/policy-cicd-seguro' },
                { type: 'doc', id: 'assets/policies/policy-gestao-segredos' },
                { type: 'doc', id: 'assets/policies/policy-release-seguro' },
                { type: 'doc', id: 'assets/policies/policy-aprovacao-release' },
                { type: 'doc', id: 'assets/policies/policy-deploy-seguro' },
                { type: 'doc', id: 'assets/policies/policy-rollback' },
              ],
            },
            {
              type: 'category',
              label: 'Infraestrutura',
              items: [
                { type: 'doc', id: 'assets/policies/policy-iac-seguro' },
                { type: 'doc', id: 'assets/policies/policy-aprovacao-plan-iac' },
                { type: 'doc', id: 'assets/policies/policy-containers-seguros' },
                { type: 'doc', id: 'assets/policies/policy-golden-base-images' },
              ],
            },
            {
              type: 'category',
              label: 'Testes',
              items: [
                { type: 'doc', id: 'assets/policies/policy-dast-fuzzing' },
                { type: 'doc', id: 'assets/policies/policy-estrategia-testes' },
                { type: 'doc', id: 'assets/policies/policy-pentesting' },
              ],
            },
            {
              type: 'category',
              label: 'Operações & Monitorização',
              items: [
                { type: 'doc', id: 'assets/policies/policy-monitorizacao-pos-deploy' },
                { type: 'doc', id: 'assets/policies/policy-logging-estruturado' },
                { type: 'doc', id: 'assets/policies/policy-monitorizacao-seguranca' },
                { type: 'doc', id: 'assets/policies/policy-gestao-alertas' },
                { type: 'doc', id: 'assets/policies/policy-irp' },
              ],
            },
            {
              type: 'category',
              label: 'Governação',
              items: [
                { type: 'doc', id: 'assets/policies/policy-rastreabilidade' },
                { type: 'doc', id: 'assets/policies/policy-rastreabilidade-organizacional' },
                { type: 'doc', id: 'assets/policies/policy-kpis-governacao' },
                { type: 'doc', id: 'assets/policies/policy-contratacao-segura' },
                { type: 'doc', id: 'assets/policies/policy-formacao-seguranca' },
              ],
            },
          ],
        },
      ],
    },
  ],

  // === 000 - Theory of Everything (Minimalista) ===
  toeOverview: [{ type: 'autogenerated', dirName: '000-teory-of-everything' }],

  // === 002 - Cross-check normativo ===
  toeCrossCheck: [{ type: 'autogenerated', dirName: '002-cross-check-normativo' }],

};

export default sidebars;
