#!/usr/bin/env python3
"""Derive the translation synchronisation state of every corpus file.

States are never declared by hand (README rule 6). Each file's state is
derived from hashes only:

* the current source hash versus ``translation.source_sha256`` recorded in the
  mirror's front matter;
* the current hash of the translated body (the mirror file without its
  ``translation`` block) versus the recorded ``translation.target_sha256``;
* the recorded ``translation.glossary_sha256`` versus
  ``common.glossary_sha256(<current registry>, translation.glossary_keys)`` —
  the hash of the registry entries the translation actually applied, reduced
  to the fields that matter (``common.GLOSSARY_HASH_FIELDS``); a key that has
  left the registry counts as a change, editing ``notes``/``evidence``/… does
  not. ``translation.terms_sha256`` (whole registry) is provenance only.
  Mirrors stamped before this field existed (no ``glossary_sha256``) fall back
  to comparing ``terms_sha256`` with the current registry hash and raise a
  "legacy provenance" warning — re-stamp them with ``translate.py assemble``.
  While the registry does not exist ``stale-terms`` can never occur;
* the number of ``<!-- i18n:pending … -->`` markers in the mirror.

Precedence when several conditions hold:
``drift > en-ahead > pt-ahead > stale-terms > partial > synced``.

Usage::

    python translation/scripts/sync_state.py --write    # regenerate translation/state/sync-state.json
    python translation/scripts/sync_state.py --check    # exit 1 if the committed file is not reproducible
    python translation/scripts/sync_state.py            # print the derived state to stdout

Exit status: 0 on success, 1 when ``--check`` finds a difference, 2 on errors
(including a mirror file whose ``translation`` block is missing or malformed —
such a file cannot have been generated by ``translate.py``).
"""

from __future__ import annotations

import argparse
import unicodedata
import os
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Tuple

sys.path.insert(0, str(Path(__file__).resolve().parent))

import common  # noqa: E402

STATES = ("untranslated", "synced", "partial", "pt-ahead", "en-ahead", "drift", "stale-terms")

# The state names carry the Phase 1 locale names by contract ("pt-ahead",
# "en-ahead"); semantically they mean "source ahead" and "target ahead".
STATE_SOURCE_AHEAD = "pt-ahead"
STATE_TARGET_AHEAD = "en-ahead"


def _as_str(value) -> Optional[str]:
    if value is None:
        return None
    return str(value)


def terms_registry_sha256(root: Path, registry: Optional[Path] = None) -> Optional[str]:
    """Hash of the terms registry (``--registry``, default ``<root>/translation/terms/registry.yaml``);
    ``None`` while the file does not exist."""
    registry = Path(registry) if registry is not None else root / common.TERMS_REGISTRY_RELPATH
    if registry.is_file():
        return common.file_sha256(registry)
    return None


def load_registry(root: Path, registry: Optional[Path] = None) -> Optional[Dict]:
    """The terms registry as a mapping (``None`` while the file does not exist)."""
    registry = Path(registry) if registry is not None else root / common.TERMS_REGISTRY_RELPATH
    if not registry.is_file():
        return None
    data = common.yaml_load(common.read_text(registry))
    if not isinstance(data, dict) or not isinstance(data.get("terms"), list):
        raise common.TranslationToolError(f"{registry}: not a registry (expected a mapping with a 'terms' list)")
    return data


LEGACY_PROVENANCE_WARNING = "legacy provenance: re-stamp with assemble"


def derive_state(
    *,
    source_hash: str,
    recorded_source_hash: Optional[str],
    target_body_hash: Optional[str],
    recorded_target_hash: Optional[str],
    terms_hash: Optional[str],
    recorded_terms_hash: Optional[str],
    pending_blocks: int,
    translated: bool,
    glossary_hash: Optional[str] = None,
    recorded_glossary_hash: Optional[str] = None,
) -> str:
    """Apply the README conditions and precedence.

    ``stale-terms`` is decided by the applied-glossary hash when the mirror
    recorded one (``recorded_glossary_hash``; ``glossary_hash`` is its current
    value, ``None`` while there is no registry). Without it — legacy mirrors —
    the whole-registry ``terms_sha256`` comparison applies.
    """
    if not translated:
        return "untranslated"
    source_changed = recorded_source_hash != source_hash
    target_changed = recorded_target_hash != target_body_hash
    if source_changed and target_changed:
        return "drift"
    if target_changed:
        return STATE_TARGET_AHEAD
    if source_changed:
        return STATE_SOURCE_AHEAD
    if recorded_glossary_hash is not None:
        terms_stale = glossary_hash is not None and glossary_hash != recorded_glossary_hash
    else:
        terms_stale = terms_hash is not None and recorded_terms_hash != terms_hash
    if terms_stale:
        return "stale-terms"
    if pending_blocks > 0:
        return "partial"
    return "synced"


def _mirror_root(target: Path, rel: str) -> Path:
    """The directory `target` is relative to, i.e. the mirror root for `rel`."""
    root = target.resolve()
    for _ in Path(rel).parts:
        root = root.parent
    return root


def file_entry(rel: str, source: Path, target: Path, terms_hash: Optional[str], source_locale: str, warnings: List[str], registry: Optional[Dict] = None) -> Dict:
    """State entry for one corpus file. ``registry`` is the current terms
    registry (mapping) used to recompute the applied-glossary hash; ``None``
    while it does not exist (then neither variant of ``stale-terms`` fires)."""
    source_hash = common.file_sha256(source)
    entry: Dict = {
        "state": "untranslated",
        "source_sha256": source_hash,
        "translated_source_sha256": None,
        "target_sha256": None,
        "terms_sha256_at_translation": None,
        "glossary_sha256_at_translation": None,
        "translated_at": None,
        "pending_blocks": 0,
    }
    if not target.is_file():
        return entry

    link_rel: Optional[str] = None
    if target.is_symlink():
        # A source symlink is mirrored as an identical relative symlink (translate.py); the entry
        # follows the link target: same hashes and state, plus `symlink_to` for the reader.
        resolved = (target.parent / os.readlink(target)).resolve()
        try:
            link_rel = resolved.relative_to(_mirror_root(target, rel)).as_posix()
        except ValueError:
            link_rel = None
        link_rel = unicodedata.normalize("NFC", link_rel) if link_rel else None
        entry["symlink_to"] = link_rel

    text = common.read_text(target)
    try:
        frontmatter, _body, _start = common.parse_frontmatter(text, where=rel)
    except common.FrontmatterError as exc:
        warnings.append(str(exc))
        frontmatter = None
    block = (frontmatter or {}).get(common.TRANSLATION_BLOCK_KEY)
    if not isinstance(block, dict):
        warnings.append(f"{rel}: mirror file has no `translation` block in its front matter (was it generated by translate.py?)")
        block = {}
    else:
        if block.get("source_locale") not in (None, source_locale):
            warnings.append(f"{rel}: translation.source_locale is {block.get('source_locale')!r}, expected {source_locale!r}")
        if block.get("source_path") not in (None, rel, link_rel):
            warnings.append(f"{rel}: translation.source_path is {block.get('source_path')!r}, expected {rel!r}")

    body_hash = common.content_sha256(common.strip_translation_block(text))
    pending = len(common.PENDING_MARKER_RE.findall(text))
    recorded_source = _as_str(block.get("source_sha256"))
    recorded_target = _as_str(block.get("target_sha256"))
    recorded_terms = _as_str(block.get("terms_sha256"))
    recorded_glossary = _as_str(block.get("glossary_sha256"))
    glossary_keys = block.get("glossary_keys")
    glossary_hash: Optional[str] = None
    if recorded_glossary is not None and not isinstance(glossary_keys, list):
        warnings.append(f"{rel}: translation.glossary_sha256 is recorded but translation.glossary_keys is not a list; {LEGACY_PROVENANCE_WARNING}")
        recorded_glossary = None
    if recorded_glossary is None:
        if block and terms_hash is not None:
            warnings.append(f"{rel}: no translation.glossary_sha256 in the front matter — stale-terms falls back to the whole-registry terms_sha256; {LEGACY_PROVENANCE_WARNING}")
    elif registry is not None:
        glossary_hash = common.glossary_sha256(registry, [str(k) for k in glossary_keys])

    entry.update(
        {
            "state": derive_state(
                source_hash=source_hash,
                recorded_source_hash=recorded_source,
                target_body_hash=body_hash,
                recorded_target_hash=recorded_target,
                terms_hash=terms_hash,
                recorded_terms_hash=recorded_terms,
                pending_blocks=pending,
                translated=True,
                glossary_hash=glossary_hash,
                recorded_glossary_hash=recorded_glossary,
            ),
            "translated_source_sha256": recorded_source,
            "target_sha256": body_hash,
            "terms_sha256_at_translation": recorded_terms,
            "glossary_sha256_at_translation": recorded_glossary,
            "translated_at": _as_str(block.get("translated_at")),
            "pending_blocks": pending,
        }
    )
    return entry


def build_state(root: Path, docs_dir: Path, i18n_dir: Path, source_locale: str, target_locale: str, *, generated_at: Optional[str] = None, registry: Optional[Path] = None) -> Tuple[Dict, List[str]]:
    warnings: List[str] = []
    terms_hash = terms_registry_sha256(root, registry)
    registry_data = load_registry(root, registry)
    files: Dict[str, Dict] = {}
    for rel in common.iter_corpus(docs_dir):
        files[rel] = file_entry(
            rel,
            common.source_path(rel, docs_dir),
            common.mirror_path(rel, i18n_dir, target_locale),
            terms_hash,
            source_locale,
            warnings,
            registry=registry_data,
        )
    source_set = set(files)
    for rel in common.iter_mirror(i18n_dir, target_locale):
        if rel not in source_set:
            warnings.append(f"{rel}: translated file has no source (orphan in the {target_locale} mirror)")
    totals = {state: 0 for state in STATES}
    for entry in files.values():
        totals[entry["state"]] += 1
    state = {
        "generated_at": generated_at or datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "source_locale": source_locale,
        "target_locale": target_locale,
        "terms_sha256": terms_hash,
        "files": {rel: files[rel] for rel in sorted(files)},
        "totals": totals,
    }
    return state, warnings


def dumps(state: Dict) -> str:
    return json.dumps(state, indent=2, ensure_ascii=False) + "\n"


def _without_generated_at(state: Dict) -> Dict:
    return {k: v for k, v in state.items() if k != "generated_at"}


def diff_states(committed: Dict, fresh: Dict) -> List[str]:
    """Human-readable differences between two state documents (ignoring generated_at)."""
    lines: List[str] = []
    a, b = _without_generated_at(committed), _without_generated_at(fresh)
    for key in ("source_locale", "target_locale", "terms_sha256", "totals"):
        if a.get(key) != b.get(key):
            lines.append(f"{key}: committed {a.get(key)!r} != derived {b.get(key)!r}")
    a_files, b_files = a.get("files", {}) or {}, b.get("files", {}) or {}
    for rel in sorted(set(a_files) | set(b_files)):
        if rel not in b_files:
            lines.append(f"{rel}: in committed state but not in the corpus")
        elif rel not in a_files:
            lines.append(f"{rel}: in the corpus but missing from the committed state")
        elif a_files[rel] != b_files[rel]:
            changed = [k for k in set(a_files[rel]) | set(b_files[rel]) if a_files[rel].get(k) != b_files[rel].get(k)]
            lines.append(f"{rel}: fields differ ({', '.join(sorted(changed))}); committed state {a_files[rel].get('state')!r}, derived {b_files[rel].get('state')!r}")
    for key in sorted(set(a) | set(b)):
        if key not in ("source_locale", "target_locale", "terms_sha256", "totals", "files") and a.get(key) != b.get(key):
            lines.append(f"{key}: committed {a.get(key)!r} != derived {b.get(key)!r}")
    return lines


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--source-locale", default=common.DEFAULT_SOURCE_LOCALE)
    parser.add_argument("--target-locale", default=common.DEFAULT_TARGET_LOCALE)
    parser.add_argument("--docs-dir", type=Path, default=None, help="source corpus root (default: <repo>/manuals_src/docs/sbd-toe)")
    parser.add_argument("--i18n-dir", type=Path, default=None, help="i18n root (default: <repo>/manuals_src/i18n)")
    parser.add_argument("--state-file", type=Path, default=None, help=f"state file (default: <repo>/{common.SYNC_STATE_RELPATH})")
    parser.add_argument("--registry", type=Path, default=None, help=f"terms registry hashed as terms_sha256 (default: <repo>/{common.TERMS_REGISTRY_RELPATH}; null while absent)")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="write the derived state to the state file")
    mode.add_argument("--check", action="store_true", help="fail if the committed state file is not reproducible")
    return parser


def main(argv=None) -> int:
    args = build_parser().parse_args(argv)
    try:
        root = common.repo_root()
        docs_dir = args.docs_dir or common.default_docs_dir(root)
        i18n_dir = args.i18n_dir or common.default_i18n_dir(root)
        state_file = args.state_file or (root / common.SYNC_STATE_RELPATH)
        registry = args.registry or (root / common.TERMS_REGISTRY_RELPATH)
        state, warnings = build_state(root, docs_dir, i18n_dir, args.source_locale, args.target_locale, registry=registry)
    except common.TranslationToolError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    for message in warnings:
        common.warn(message)

    if args.write:
        state_file.parent.mkdir(parents=True, exist_ok=True)
        state_file.write_text(dumps(state), encoding="utf-8")
        print(f"wrote {state_file} — " + ", ".join(f"{k}={v}" for k, v in state["totals"].items()))
    elif args.check:
        if not state_file.is_file():
            print(f"error: {state_file} does not exist; run with --write first", file=sys.stderr)
            return 1
        try:
            committed = json.loads(state_file.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            print(f"error: {state_file} is not valid JSON: {exc}", file=sys.stderr)
            return 1
        differences = diff_states(committed, state)
        if differences:
            print(f"{state_file} is stale ({len(differences)} difference(s)); regenerate with --write:")
            for line in differences[:50]:
                print(f"  {line}")
            if len(differences) > 50:
                print(f"  … {len(differences) - 50} more")
            return 1
        print(f"{state_file} is reproducible — " + ", ".join(f"{k}={v}" for k, v in state["totals"].items()))
    else:
        sys.stdout.write(dumps(state))
    return 2 if warnings else 0


if __name__ == "__main__":
    sys.exit(main())
